version: '3.5'

services:
  server:
    container_name: go_server_container
    build: ./server  
    depends_on: 
      - postgres
    restart: unless-stopped
    ports: 
      - 8080:8080
    networks:
      - motivapp

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-magicalpassword}
      POSTGRES_DB: ${POSTGRES_DB:-MotivApp_Database}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - motivapp
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "9000:80"
    networks:
      - motivapp
    restart: unless-stopped

networks:
  motivapp:
    driver: bridge

volumes:
    postgres:
    pgadmin:
